site_name: Echarts geomapping
repo_url: https://github.com/echarts-maps/echarts-geomapping-book
edit_uri: edit/master/book/


nav:
  - HOME: index.md
  - Tools:
    - geojson.io: tools/geojson-io.md
    - mapshaper: tools/mapshaper.md
    - echarts-mapmaker: tools/mapmaker.md
    - GDAL: tools/gdal.md
    - Geojson data source: geojson-sources.md
  - Tutorial:

    - Draw The Forbidden City: tutorial/101.md
    - Integrate with pyecharts: tutorial/102.md
    - Render The Forbidden City using pyecharts: tutorial/103.md
    - Bring The Forbidden City into jupyter notebook: tutorial/104.md
    - Sharing The Forbidden City with others: tutorial/105.md
  - Use Cases:
    - Make a contour of Beijing: howtos/dissolve-internal-borders.md
    - Where do the county maps come from?: howtos/split-geojson.md
    - Make northern China map: howtos/split-and-merge.md
    - How to remove an internal border: howtos/remove-an-internal-border.md
    - Create new geo shape and append it: howtos/add-ji-zhou-qu-to-tianjin.md
    - Source Switzerland map from natural earth data: howtos/switzerland.md


docs_dir: book
site_dir: docs

markdown_extensions:
  - codehilite
